### ISSUE TITLE
epub: Empty pages caused by `page-break-*` style on block level elements

### ISSUE THREAD

**Issue by luxvw** [sumatrapdfreader/sumatrapdf#3267]
For example, we have multiple chapters stuffed in single (x)html, wrapped in sections.

```html
<html>
<section>Chapter1 …</section>
<section>Chapter2 …</section>

<html>
<section>Chapter3 …</section>
<section>Chapter4 …</section>
```

To manually break chapters to display each chapter on a new page, 
we apply `page-break-*` style to `<section>`.

```css
section { page-break-after:always; margin-top:20%; }
```

In this case, a blank page is inserted before Chapter3, possibly due to a file-level page break that is not merged with block-level page break.

The following is okay, except that the top margin won't apply.

```css
section + section { page-break-before:always; margin-top:20%; }
```
